[Variables]
Green=128,213,135
Blue=120,184,224
Yellow=237,207,66
Red=227,59,65
DarkGreen=56,147,62
DarkBlue=52,116,155
Indigo=0,85,136
Pink=240,65,100
NvidiaGreen=118,185,0
Orange=255,120,0

CPU1BarColor=#Blue#,200
CPU2BarColor=#Green#,200
CPU3BarColor=#Yellow#,200
CPU4BarColor=#Red#,200
CPU1LineColor=#Blue#,175
CPU2LineColor=#Green#,175
CPU3LineColor=#Yellow#,200
CPU4LineColor=#Red#,200

RAMGraphColor=#Pink#,70
RAMBarColor=#Pink#,200
RAMLineColor=#Pink#

GPUGraphColor=#NvidiaGreen#,70
GPUBarColor=#NvidiaGreen#,200
GPULineColor=#NvidiaGreen#
GPURAMLineColor=#Orange#
GPURAMBarColor=#Orange#,200

DownloadBarColor=#Blue#,200
DownloadLineColor=#DarkBlue#
UploadBarColor=#Green#,200
UploadLineColor=#DarkGreen#

HDDBarColor=#Indigo#,200
HDDLineColor=#Blue#

VolumeBarColor=51,181,229
VolumeBarBackgroundColor=54,54,54

VUMeterLineColor=#Orange#
VUMeterBarColor=#Orange#,70

[MainTextStyle]
FontColor=255,255,255
FontFace=GeosansLight
FontSize=18
AntiAlias=1

[SmallTextStyle]
FontColor=200,200,200
FontSize=14

[RightTextStyle]
StringAlign=Right

[BarDimension]
W=20
H=80

[BarBackgroundStyle]
ImageName=#@#Images\Skin\barBackground.png
PreserveAspectRatio=2

[HorizontalBarDimension]
W=220
H=35
BarOrientation=Horizontal

[HorizontalBarBackgroundStyle]
ImageName=#@#Images\Skin\horizontalBarBackground.png
PreserveAspectRatio=2

[GraphDimension]
W=260
H=80

[GraphBackgroundStyle]
ImageName=#@#Images\Skin\graphBackground.png
PreserveAspectRatio=2

[PieDimensions]
W=80
H=80

[PieStyle]
X=0r
Y=0r
W=80
H=80
StartAngle=3.1415
RotationAngle=6.283
Solid=1
AntiAlias=1