[Variables]

; CPU name in Open Hardware Monitor
MCPU=Intel Core i5-4670K
; GPU name in Open Hardware Monitor
MGPU=NVIDIA GeForce GTX 970

; CPU mode (0=bar graphs, 1=pie charts)
; You can also click on the vertical bars/pie chart zone to change the mode
CPUMode=0

; Query for http://openweathermap.org
WeatherQ=Lyon

; Language for http://openweathermap.org
WeatherLang=fr

; API key for http://openweathermap.org
WeatherApiKey=

; Weather icons theme (0=white, 1=colorful)
; You can also click on the weather icon to change the theme
WeatherTheme=1

; Drives letters
Drive1=B:
Drive2=C:
Drive3=D:

; Date translation using substitution
; WARNING: Because Substitute does not stop at first match, we cannot mix long and short names
DateTranslation="January":"Janvier","February":"Février","March":"Mars","April":"Avril","May":"Mai","June":"Juin","July":"Juillet","August":"Août","September":"Septembre","October":"Octobre","November":"Novembre","December":"Décembre","Sun":"Dim","Mon":"Lun","Tue":"Mar","Wed":"Mer","Thu":"Jeu","Fri":"Ven","Sat":"Sam"

;"January":"Janvier","February":"Février","March":"Mars","April":"Avril","May":"Mai","June":"Juin","July":"Juillet","August":"Août","September":"Septembre","October":"Octobre","November":"Novembre","December":"Décembre"
;"Jan":"Jan","Feb":"Fév","Mar":"Mars","Apr":"Avril","May":"Mai","Jun":"Juin","Jul":"Juil","Aug":"Août","Sep":"Sept","Oct":"Oct","Nov":"Nov","Dec":"Dec"
;"Sunday":"Dimanche","Monday":"Lundi","Tuesday":"Mardi","Wednesday":"Mercredi","Thursay":"Jeudi","Friday":"Vendredi","Saturday":"Samedi"
;"Sun":"Dim","Mon":"Lun","Tue":"Mar","Wed":"Mer","Thu":"Jeu","Fri":"Ven","Sat":"Sam"
