[Variables]

; CPU name in Open Hardware Monitor
MCPU=Intel Core i5-4670K
; GPU name in Open Hardware Monitor
MGPU=NVIDIA GeForce GTX 970

; Query for http://openweathermap.org
WeatherQ=Lyon,fr
; Language for http://openweathermap.org
WeatherLang=fr
; Weather icons theme (1=colorful or 2=white)
WeatherTheme=1

; Drives letters
Drive1=B:
Drive2=C:
Drive3=D:

; Date translation using substitution
; WARNING: Because Substitute does not stop at first match, we cannot mix long and short names
DateTranslation="January":"Janvier","February":"Février","March":"Mars","April":"Avril","May":"Mai","June":"Juin","July":"Juillet","August":"Août","September":"Septembre","October":"Octobre","November":"Novembre","December":"Décembre","Sun":"Dim","Mon":"Lun","Tue":"Mar","Wed":"Mer","Thu":"Jeu","Fri":"Ven","Sat":"Sam"

;"January":"Janvier","February":"Février","March":"Mars","April":"Avril","May":"Mai","June":"Juin","July":"Juillet","August":"Août","September":"Septembre","October":"Octobre","November":"Novembre","December":"Décembre"
;"Jan":"Jan","Feb":"Fév","Mar":"Mars","Apr":"Avril","May":"Mai","Jun":"Juin","Jul":"Juil","Aug":"Août","Sep":"Sept","Oct":"Oct","Nov":"Nov","Dec":"Dec"
;"Sunday":"Dimanche","Monday":"Lundi","Tuesday":"Mardi","Wednesday":"Mercredi","Thursay":"Jeudi","Friday":"Vendredi","Saturday":"Samedi"
;"Sun":"Dim","Mon":"Lun","Tue":"Mar","Wed":"Mer","Thu":"Jeu","Fri":"Ven","Sat":"Sam"