[Variables]

; CPU name in Open Hardware Monitor
MCPU=Intel Core i5-4670K
; GPU name in Open Hardware Monitor
MGPU=NVIDIA GeForce GTX 970

; CPU mode (0=bar graphs, 1=pie charts)
; You can also click on the vertical bars/pie chart zone to change the mode
CPUMode=0

; Query for http://openweathermap.org
WeatherQ=Lyon

; Language for http://openweathermap.org
WeatherLang=fr

; API key for http://openweathermap.org
WeatherApiKey=

; Weather icons theme (0=white, 1=colorful)
; You can also click on the weather icon to change the theme
WeatherTheme=1

; Replace the clock by 3-days forecast
Forecast=1

; Drives letters
Drive1=B:
Drive2=C:
Drive3=D:
